### ISSUE TITLE
1.9 Compatibility

### ISSUE THREAD

**Issue by abedra** [abedra/mpi-ruby#3]

**Comment by chadbrewbaker** [comment]
I ported Ruby to the Blue Gene/L along with Rudi Cilibrasi's MPI bindings back around 2006.  Glad to see someone is still maintaining a package. If you need any more C bindings ( All-to-all was a pain if I remember) I can bring it out of mothballs.  

My end goal which I never reached was making a robust set of Ruby libraries on top of MPI. One Ruby interpreter per CPU. Sorting, graph computations, molecular dynamics (with calls down to C kernels of course) ....
